name: score_board
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^10.0.1
  bloc: ^7.0.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.2.1
  intl: 0.19.0

dev_dependencies:
  auto_route_generator: ^10.0.1
  bloc_test: ^8.0.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  # mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
